version: '3'
services:
    todo-postgres:
        image: postgres:13
        
        environment:
            POSTGRES_USER: ikhzan
            POSTGRES_PASSWORD: rahasia
            POSTGRES_DB: belajar
        ports:
            - "5432:5432"
        volumes:
            - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    
    todo-backend:
        build: ./backend
        ports:
            - "8080:8080"
        environment:
            - DB_USER=ikhzan
            - DB_PASSWORD=rahasia
            - DB_HOST=todo-postgres
            - DB_PORT=5432
            - DB_DATABASE=belajar

        depends_on:                     #dijalankan setelah service todo-postgres berjalan
            - todo-postgres

    todo-frontend:
        build: ./frontend
        ports:
            - "8081:8080"